sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: U+0B5Z7hYG2M7hlAK7bwyD/w+IHgIOX86wITX/S8OQ/RQ/P1Ynni6K2mEDrt7R2ECaSFxb2Wjb9lfRjiiD0NyjQsf2NKP+SUMbgENhTHaIJpaEhQJpFToiBNRpn/urarXpW1bQaPIBUi2RHyK0jvk6C4bWWS9xnr6jjK6CO/oCUoV9V63uNHi9mVyalMXW5eXwGRMemVUAhDkmXL+7GfBe6hurxp+y6GuKBSLvLetVml37unKuz3cGws+AL7+ZDPNeO5IrxonHEWsDbC6mRPrSBfH2aOWpj8RyJ+1Cv0J9iwk+38mHApptO7OkR9eWFe329rEcTQ+Bz7Q+C/LpbIdcT3xGaKVDeNux4Z2mtg8OGn5DmlImyUk30lIboh/1OQpy7JS59t+snSUa9S16/79xIk8KOubJTrK2D63Z7AU8OrX3l++Crd5+Fj2V6aktV3ZrAcNZfiVcIAxkKQKK0V11+lGrXR0W3AABSj6EerQyfphAy7AcJcMe+Zx+IYdygPejW6a95tlclHoJHUbPPe91oLN3ibx7SfOixBGGM5t6Si0j6gcgyuxezqPjmF6ReGvtlBsoKHzWX0a9NtlSpb7adq1Jy+Eu9AiWZRWHDsmCfUI+YgL5xJGFnjVEjKDZnRIo37ERlWsJ7eCqafYCbDBOVOv0EN2Hsr847/3/EykL0=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Ward-of-King-Canute--A-Romance-of-the-Danish-Conquest_3323
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy